# Site settings
title: 'Gaurav Singh'
email: 'gaurav88point@gmail.com'
description: 'A dark blog theme for Jekyll.'
baseurl: ''
url: 'http://null-sys.github.io/'
title_description: 'A darg on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect.'
title_image: '/assets/null-sys.png'
google_analytics: 'UA-20365477-4'
disqus_account: cartenoire
github_repository: https://github.com/null-sys
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: Gaurav86292287
github_username: null-sys
instagram_username: untagged.sparrow
reddit_username:
linkedin_link: https://www.linkedin.com/in/gaurav-singh-5569b3190/
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_right: 'Made with <i class="fa fa-heart"></i> by <a href="https://github.com/null-sys"">Gaurav</a>'
#footer_right: '&lt;/&gt; on <a href="https://github.com/null-sys">Github</a> &nbsp;<i class="fa fa-github-alt"></i>'

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
